### PR TITLE
Enhancement: TLG order

### LINKED ISSUE #51: Enhancement: Add a TLG order tab
### Description
We would need to create a new tab in the Shiny app top order the TLGs:

Create a tab called 'TLGs' where all the TLGs will be requested, list all of them, and select the appropriate one by default (if we have urine data in the TLGs, pre-select Urine TLGs).

### Definition of Done
The requirements for the feature to be complete:
- [ ] make sure to test if there are Urine variables, if yes, pre-select the TLGs that are Urine related by default
- [ ] Make sure to have the following variables in the data ordering, for example:
0. TLG  = "Table", "Listing" or "Graph"
00. Dataset = "ADPC" or "ADPP"
1. TLG name = "PKCG01" xwith the link to https://insightsengineering.github.io/tlg-catalog/stable/graphs/pharmacokinetic/pkcg01.html
2. Function name = "g_pkconc_lin"
3. . Title (already populated)= "Individual plots of concentrations vs. time (one plot per patient/subject)"
4. Footnote = "" -> free text for the user
5. Stratification = "" -> drop-down menu with the available variables of ADPC/ADNCA. By default ""
6. Condition = "IV" or ""
7. Comment = "" -> free text for the user

- [ ] The user should be able to add a new line of TLG request (later on, we will think about a strategy about the TLG custom - if to send an email to someone to do this TLG, or implement it into the app) -> Add custom button, and export tlg order as csv button
- [ ] Be able to filter the columns easily via a shiny table
- [ ] Button submit needed. to apply all the changes later on

This is an example of how it may look like:
image

### PR DESCRIPTION
**Pull request by Gero1999**
## Issue

Closes #51 #52 

## Description
Create a tab called 'TLGs' where all the TLGs will be requested, list all of them, and select the appropriate one by default (if we have urine data in the TLGs, pre-select Urine TLGs).
Change description.

## Definition of Done #51 
 - [x] Make sure to test if there are Urine variables, if yes, pre-select the TLGs that are Urine related by default
 - [x] Make sure to have the following variables: TLG, Dataset, Function, Title, Footnote, Stratification, Condition, Comment
 - [x] Be able to filter the columns easily via a shiny table
 - [x]  Button submit needed. to apply all the changes later on. **Should either be accessible or 2 buttons (above/below)**

## Definition of Done #52
Once the button Submit is clicked:
- [x] two new tabs are updated: Table, Graph, List (by default there are already created but empty).
- [x] in each tabs, we have a left panel where you select the TLG that you want to view. (with the Function name (for now)) - Panel: size 20 %
- [x] On the right panel, you will have the customization options (not yet populated) - just create the Panel: size 20 %
- [x] In the middle panel, you will have the plot (not yet populated) - just create the Panel: size 60 %
- [x] Make sure that when you submit again the button with another TLG selection, all the TLGs function names are being updated

## How to test #51 
- [x] Check TLG table includes all variables needed
- [x] Make sure the table preselects by default the rows indicated in $Select and also those where $Condition is true for the ADNCA tested
- [x] When button submit is pressed, the print() action shows the filtered dataset
- [x] Links to the functions are working and correct

## How to test #52
- [x] Easy resetting of TLG order
- [x] Sub-tabs in Tables / Listings / Graphs are updated when different TLGs are ordered
- [x] Three clear separated spaces in the Tables / Listings / Graphs tabs
- [x] Check new additions (1. TLG in 2 tables: selected and not,  2. Disable edition of unneeded columns)

## Easy additions requested
- [x] Disable edition of some columns, separate in style.css 
- [x] Separate TLGs selected from the ones that were not

## Contributor checklist
- [x] Solve conflicts before merging

### CODE REVIEW

**Comment by Gero1999** [comment]
Original dataset was changed because links were wrongly annotated. The correction was done with the next code:

```
TLG_order = read.csv('www/data/TLG_order_details.csv', row.names = F) %>% 
  mutate(
    Catalog_Link = paste0("https://insightsengineering.github.io/tlg-catalog/stable/", tolower(Type), 's', '/pharmacokinetic/', PKid, '.html')
  )
```

**Comment by Shaakon35** [comment]
Later, this could be improved by:
- eventually have the selected TLGs on top only, and the not selected below
- freeze some columns (avoid free text) to avoid the user to change everything
- button to go back by default
- remove the numbers in the first row 1 to 40
- add the TLGs from GSK
- some colors code (adpc, adpp, t, l, g)
- resize the columns correctly

**Comment by m-kolomanski** [comment]
Hey, a suggestion on that one:

Since this part of the application seems quite detached from what is going on currently, I think this is prime functionality to start wrapping things up into [shiny modules](https://shiny.posit.co/r/articles/improve/modules/). I can convert what already has been done into a module and then we can go from there, what do you think?

**Comment by Gero1999** [comment]
> @Gero1999 Hey, a suggestion on that one:
> 
> Since this part of the application seems quite detached from what is going on currently, I think this is prime functionality to start wrapping things up into [shiny modules](https://shiny.posit.co/r/articles/improve/modules/). I can convert what already has been done into a module and then we can go from there, what do you think?

Hey @m-kolomanski! For me is fine! I was planning to use modules more for the next requirements (#52 ) but if you think transforming what is currently makes it better I can also take it as an example

**Comment by Gero1999** [comment]
@Shaakon35 Feel free to check if the panels sizes are good for you, I included some text to make it intuitive, although I guess that the final implementations and changes of this will be done in #53

**Review by Shaakon35 — APPROVED** [review]
all good

**Pull request merged**
