### PR TITLE
Enhancement: allow to color by multiple variables individual plots

### LINKED ISSUE #91: Bug: Individual plots grouping
### Description
Individual plots have grouping options, but no default. And no option for multiple groups.
### To reproduce
Outputs -> Individual Plots

### Expected behaviour
Individual plots should always be grouped by USUBJID, with the option to ALSO group by other variables. And multiple variables can be selected.

### PR DESCRIPTION
**Pull request by Gero1999**
## Issue

Closes #91

## Description
Individual plots have grouping options, but no default. And no option for multiple groups.

## Definition of Done
Individual plots should always be grouped by USUBJID, with the option to ALSO group by other variables. And multiple variables can be selected.

## How to test
- [x] Individual plots should always be grouped by USUBJID, 
- [x] Individual plots can be grouped  by multiple variables

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented

## Notes to reviewer

Anything that the reviewer should know before tacking the pull request?

### CODE REVIEW

**Review by js3110 — APPROVED** [review]
Looks good! nice one

**Comment by js3110** [comment]
@Gero1999 maybe you can add implement tests to the function before you merge?

**Comment by Gero1999** [comment]
Hello @js3110. What test/function are you thinking of?

**Comment by js3110** [comment]
@Gero1999 i mean implement testthat for the lineplot function. just cos we need to slowly implement it for all the functions so its easier to add it each time we change one of them rather than having to go through each one if that makes sense! :)

**Comment by Gero1999** [comment]
Hey @js3110, implemented the testthat with the sample data and detected a "bug" due to an unneeded select(). Let me know if things look good now.

- [ ] testthat implementation
- [ ] functionality keeps working as expected

**Review by js3110 — APPROVED** [review]
nice !!

**Pull request merged**
