### PR TITLE
Bug: individual plots log scale

### LINKED ISSUE #118: Bug: Individual plots log scale
### Description
Log scale of individual plots not working

### To reproduce
Outputs -> Ind plots -> log scale

### Expected behaviour

- [x] Should correctly transform to log
- [x] Values =0 filtered out (only for log scale)
- [x] Plot follows same steps as the mean plot counterpart

### PR DESCRIPTION
**Pull request by js3110**
## Issue

Closes #118 

## Description

Log scale of individual plots not working

## Definition of Done

- [x] Should correctly transform to log
- [x] Values =0 filtered out (only for log scale)
- [x] Plot follows same steps as the mean plot counterpart

## How to test

Outputs -> Individual Plots -> Log scale

## Contributor checklist
- [x] Code passes lintr checks
- [x] Code passes all unit tests
- [x] New logic covered by unit tests
- [x] New logic is documented

## Notes to reviewer

Values = 0 filtered out for log scale as 0s cannot be plotted on a log scale.

### CODE REVIEW

**Review by Gero1999 — COMMENTED** [review]
@js3110 Noticed DOSEA = 50 is not considered in Individual plots but it appears in mean plots! Could you guess why?

**Comment by js3110** [comment]
> @js3110 Noticed DOSEA = 50 is not considered in Individual plots but it appears in mean plots! Could you guess why? Might be something involving the pre-filterings I guess...

it is showing up for me.... PT 11201 for example

**Review by Gero1999 — APPROVED** [review]
right, all seems good then!

**Review by m-kolomanski — APPROVED** [review]
LGTM

**Pull request merged**
