### PR TITLE
Style: Implement lintr

### LINKED ISSUE #40: Style: Implement lintr
**Description**
The details are also up for discussion, but I believe it is necessary to define how the code should be written, so we can keep it clean, consistent and easily understandable. We can automate this process and make sure the code always adheres to the rules by utilizing [lintr](https://lintr.r-lib.org/).

### PR DESCRIPTION
**Pull request by m-kolomanski**
## Issue

Closes #40 

## Description

The details are also up for discussion, but I believe it is necessary to define how the code should be written, so we can keep it clean, consistent and easily understandable. We can automate this process and make sure the code always adheres to the rules by utilizing [lintr](https://lintr.r-lib.org/).

For setup in IDE, please follow [this guide](https://lintr.r-lib.org/articles/editors.html).

For `Rstudio`, in addition I personally recommend checking the **Provide R style diagnostics** in the Tools -> Global Options -> Code -> Diagnostics. This will display all linter issues within the editor.

For `VSCode`, I personally recommend installing [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) extension for better highlighting.

## Definition of Done

- [x] basic configuration for `lintr` implemented
- [x] details of `lintr` rules discussed and implemented in configuration
- [x] current codebase adheres to applied guidelines

## Notes to reviewer
I am unsure how to properly review those changes - due to changes in formatting, the commit touches almost every line in the codebase. The most important thing is that `devtools::lint()` runs without errors.

First and foremost, please check if all functionalities of the application that were there before remain intact - I have checked that the application works correctly to the best of my ability, but my understanding of what the app should and shoudnt do is still very limited.

### CODE REVIEW

**Comment by m-kolomanski** [comment]
Things to discuss regarding the details of implementation:

- **Style guide** -> is there any style guide we want to adhere to? The standard is [tidyverse](https://style.tidyverse.org/) guide, but we can change things to adhere to our preferences (I am not a fan of couple of rules included), as long as we are consistant.
- **Line length** -> I have bumped it from 80 to 100 due to personal preference. I think even going to 120 is fine.
- **Assignment** -> we can either use `=` or `<-` for variable assignment, using both is messy. Tidyverse guide suggests `<-`, I personally dislike it and prefer `=`. We can do whatever, as long as we are being consistant.

**Review by js3110 — CHANGES_REQUESTED** [review]
For me the app crashes as soon as it is run, due to renaming of resNCA to res_nca that has no then been changed for all occurrences. 
Warning: Error in resNCA: could not find function "resNCA"
Should be an easy find and replace all job I think!

**Comment by m-kolomanski** [comment]
@js3110 Please check again, I have just resolved merge conflicts, should be fine now.

**Review by js3110 — CHANGES_REQUESTED** [review]
Hi @m-kolomanski 

The app no longer crashes on first run however there are a number of things that do not work anymore:

- Partial AUC causes crash: AUC_mins not found (renamed auc_mins?)
- NCA Download and Settings Download as .csv not working (only .htm)
- Slope selector plots Error: object 'IX' not found, manual slope selection not possible (Error in slope_manual_NCA_data: could not find function "slope_manual_NCA_data")
- General Plotting:
- -> Individual Plots no output (Error: 'length = 24' in coercion to 'logical(1)')
- -> Mean plots also no output (Error: [object Object])
- Dose Escalation -> Box Plots also no output. No error message either.

let me know if you need more details on these issues

**Comment by m-kolomanski** [comment]
@js3110 I have fixed issues with AUC_mins and slope_manual_NCA_data, as well as download. Plots are displaying now. Please let me know how it looks to you, thank you for your help!

**Review by js3110 — CHANGES_REQUESTED** [review]
@m-kolomanski Thanks! The AUC feature is now working and the download buttons, however I am still seeing issues in the following plots:

Outputs Section
1. General plotting individual and mean plots both showing error messages
2. Dose Escalation Box Plots not showing any output (to test- it will only show after NCA is run)

NCA Section:

1. Setup -> Slope Selector no plots just error messages. In this same section the widget in the top left corner is used to create manual slopes, but if I add a manual selection the app crashes with the following message: 
Warning: Error in mutate: ℹ In argument: `exclude_half.life = { ... }`.
ℹ In group 1: `STUDYID = "XX01"`, `USUBJID = 11101`, `PCSPEC = "SERUM"`, `DOSNO =
  1`.
Caused by error in `is.excluded.hl || !is.included.hl`:
! 'length = 7' in coercion to 'logical(1)

^this is a different error to last time so you are definitely getting there lol ...

**Comment by m-kolomanski** [comment]
@js3110 

I have pushed fixes to the things you have mentioned - seems to work as expected now. Please let me know if you find anything else.

**Review by js3110 — APPROVED** [review]
I just found a small mistake where DOSNO had been accidentally written as OSNO but I changed it myself since it was so small, and now from what I can see all the features and functions are working as expected :)

**Pull request merged**
